### ISSUE TITLE
m1 安装 tidevice 成功，执行 tidevice version 报错

### ISSUE THREAD

**Issue by jiaxw32** [alibaba/taobao-iphone-device#103]
m1 上安装各种问题啊，希望可以优化解决下

执行安装脚本  `pip3 install -U "tidevice[openssl]"`

`Pillow` 报错，解决方案参考： [苹果Macbook Pro 13 M1芯片安装Pillow的正确姿势
](https://blog.csdn.net/jia611/article/details/111415011)

手动安装 `Pillow`，之后再执行安装脚本，安装成功，最终提示成功 如下：

```txt
Successfully installed cached-property-1.5.2 colored-1.4.2 logzero-1.7.0 pyOpenSSL-20.0.1 tidevice-0.4.8
```

执行 `tidevice version` 报错：

```
Traceback (most recent call last):
  File "/Users/admin/Library/Python/3.8/bin/tidevice", line 5, in <module>
    from tidevice.__main__ import main
  File "/Users/admin/Library/Python/3.8/lib/python/site-packages/tidevice/__init__.py", line 7, in <module>
    from ._device import BaseDevice as Device
  File "/Users/admin/Library/Python/3.8/lib/python/site-packages/tidevice/_device.py", line 30, in <module>
    from PIL import Image
  File "/Users/admin/Library/Python/3.8/lib/python/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/admin/Library/Python/3.8/lib/python/site-packages/PIL/_imaging.cpython-38-darwin.so, 2): no suitable image found.  Did find:
	/Users/admin/Library/Python/3.8/lib/python/site-packages/PIL/_imaging.cpython-38-darwin.so: mach-o, but wrong architecture
	/Users/admin/Library/Python/3.8/lib/python/site-packages/PIL/_imaging.cpython-38-darwin.so: mach-o, but wrong architecture
```

查看 `_imaging.cpython-38-darwin.so` 架构

```bash
file /Users/admin/Library/Python/3.8/lib/python/site-packages/PIL/_imaging.cpython-38-darwin.so
```

输出结果

```txt
/Users/admin/Library/Python/3.8/lib/python/site-packages/PIL/_imaging.cpython-38-darwin.so: Mach-O 64-bit bundle x86_64
```

**Comment by codeskyblue** [comment]
我的的是M1 python 3.9 安装完之后，看样子没什么问题

**Comment by codeskyblue** [comment]
See this issue https://github.com/python-pillow/Pillow/issues/5093  this may help you.

**Comment by jiaxw32** [comment]
这样执行可以了

```shell
$ arch -x86_64 tidevice version
```
