### ISSUE TITLE
无法启动wda

### ISSUE THREAD

**Issue by nuxim** [alibaba/taobao-iphone-device#11]
tidevice xctest -B com.facebook.WebDriverAgentRunner                
[I 210130 11:12:10 _device:909] BundleID: com.facebook.WebDriverAgentRunner
[I 210130 11:12:10 _device:911] DeviceIdentifier: 00008020-00160C200EDA002E
[I 210130 11:12:10 _device:773] SignIdentity: 'Apple Development: xxx'
[E 210130 11:12:10 _device:837] Launch failed: NSError(CODE:2 DOMAIN:com.apple.dt.deviceprocesscontrolservice INFO:{'NSLocalizedDescription': 'Request to launch '
                               'com.facebook.WebDriverAgentRunner'
                               'failed.',
     'NSLocalizedFailureReason': 'The operation couldn’t be completed. Launch '
                                 'failed : Failed to launch process with bundle '
                                 'identifier '
                                 "'com.facebook.WebDriverAgentRunner'.",
     'NSUnderlyingError': NSError(CODE:1 DOMAIN:SBWorkspaceTransaction INFO:{'NSLocalizedFailureReason': 'Launch failed',
     'SBTransaction': 'SBSuspendedWorkspaceTransaction'})})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/tidevice", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/__main__.py", line 407, in main
    actions[args.subparser](args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/__main__.py", line 203, in cmd_xctest
    d.xctest(args.bundle_id, logger=setup_logger(level=logging.INFO))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_device.py", line 982, in xctest
    pid = self._launch_wda(bundle_id, session_identifier, logger)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_device.py", line 838, in _launch_wda
    raise MuxError("Launch failed")
tidevice.exceptions.MuxError: Launch failed

**Comment by nuxim** [comment]
是app信任问题
