### ISSUE TITLE
Windows下运行tidevice list/info等报ConnectionRefusedError错误

### ISSUE THREAD

**Issue by sukekes** [alibaba/taobao-iphone-device#111]
win10 通过

`pip3 install -U "tidevice[openssl]"`

安装tidevice后并连接iOS设备

运行

`tidevice list ` 

或

`tidevice info`

等命令时出现ConnectionRefusedError错误，

具体报错信息如下：

`>tidevice info
Traceback (most recent call last):
  File "d:\software\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\software\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Software\Python39\Scripts\tidevice.exe\__main__.py", line 7, in <module>
  File "D:\Software\Python39\Lib\site-packages\tidevice\__main__.py", line 689, in main
    actions[args.subparser](args)
  File "D:\Software\Python39\Lib\site-packages\tidevice\__main__.py", line 104, in cmd_device_info
    d = _udid2device(args.udid)
  File "D:\Software\Python39\Lib\site-packages\tidevice\__main__.py", line 70, in _udid2device
    _udid = _complete_udid(udid)
  File "D:\Software\Python39\Lib\site-packages\tidevice\__main__.py", line 44, in _complete_udid
    infos = um.device_list()
  File "D:\Software\Python39\Lib\site-packages\tidevice\_usbmux.py", line 75, in device_list
    data = self.send_recv(payload)
  File "D:\Software\Python39\Lib\site-packages\tidevice\_usbmux.py", line 46, in send_recv
    with self.create_connection() as s:
  File "D:\Software\Python39\Lib\site-packages\tidevice\_usbmux.py", line 43, in create_connection
    return PlistSocket(self.__address, self._next_tag())
  File "D:\Software\Python39\Lib\site-packages\tidevice\_safe_socket.py", line 95, in __init__
    super().__init__(addr)
  File "D:\Software\Python39\Lib\site-packages\tidevice\_safe_socket.py", line 48, in __init__
    self._sock.connect(addr)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。`

![image](https://user-images.githubusercontent.com/38717537/121114287-07db2380-c846-11eb-8bf1-5b9e655dfdd6.png)

**Comment by AllenLuosong** [comment]
确定你的IOS设备正确安装了 WebDriverAgentRunner-Runner吧，看这个报错是WebDriverAgentRunner-Runner没有正常和手机通信导致

**Comment by jongyu** [comment]
你电脑装了iTunes吗

**Comment by sukekes** [comment]
> 你电脑装了iTunes吗

确实是忘记安装itunes了

**Comment by sukekes** [comment]
> 确定你的IOS设备正确安装了 WebDriverAgentRunner-Runner吧，看这个报错是WebDriverAgentRunner-Runner没有正常和手机通信导致

我这边想问下WDA是如何安装的呢，似乎没有ipa，是通过xcode打包一个安装包吗
