### ISSUE TITLE
【want-help】ios14.6版本截图失败

### ISSUE THREAD

**Issue by linmscat** [alibaba/taobao-iphone-device#118]
Traceback (most recent call last):
  File "mods\meter\sampler\device_sampler.py", line 75, in sample
  File "mods\meter\sampler\device_sampler.py", line 135, in _snapshot
  File "driver\ios\ios_appium.py", line 69, in snapshot
  File "selenium\webdriver\remote\webdriver.py", line 1032, in get_screenshot_as_file
  File "selenium\webdriver\remote\webdriver.py", line 1064, in get_screenshot_as_png
  File "selenium\webdriver\remote\webdriver.py", line 1074, in get_screenshot_as_base64
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "appium\webdriver\errorhandler.py", line 31, in check_response
  File "appium\webdriver\errorhandler.py", line 26, in check_response
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: -[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x2813c7f80

**Comment by codeskyblue** [comment]
这个应该是你使用的WDA截图不兼容，跟这个tidevice没多大的关系
