### ISSUE TITLE
已安装了itunes，使用tidevice list仍报ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by Tanliyustone** [alibaba/taobao-iphone-device#120]
报错信息如下，电脑装了itunes8
List of apple devices attached
Traceback (most recent call last):
  File "d:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python36\Scripts\tidevice.exe\__main__.py", line 7, in <module>
  File "d:\program files\python36\lib\site-packages\tidevice\__main__.py", line 715, in main
    actions[args.subparser](args)
  File "d:\program files\python36\lib\site-packages\tidevice\__main__.py", line 83, in cmd_list
    for dinfo in um.device_list():
  File "d:\program files\python36\lib\site-packages\tidevice\_usbmux.py", line 75, in device_list
    data = self.send_recv(payload)
  File "d:\program files\python36\lib\site-packages\tidevice\_usbmux.py", line 46, in send_recv
    with self.create_connection() as s:
  File "d:\program files\python36\lib\site-packages\tidevice\_usbmux.py", line 43, in create_connection
    return PlistSocket(self.__address, self._next_tag())
  File "d:\program files\python36\lib\site-packages\tidevice\_safe_socket.py", line 95, in __init__
    super().__init__(addr)
  File "d:\program files\python36\lib\site-packages\tidevice\_safe_socket.py", line 48, in __init__
    self._sock.connect(addr)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by hanwenlu2016** [comment]
我也是 请问问题解决了吗？？？

**Comment by jinjf553** [comment]
我也遇到了这个问题，但是我重启了几次电脑就好了。重启电脑时可能需要拔掉手机才行。
