### ISSUE TITLE
tidevice.exceptions.MuxReplyError: UsbmuxReplyCode.ConnectionRefused

### ISSUE THREAD

**Issue by luxiaolan6373** [alibaba/taobao-iphone-device#148]
完整的报错如下,我和之前哪位老友一样,也是用着用着就这样了,啥都没干..就是突然怎么启动都启动不了服务了,到处没找到答案 希望能够解答一下
Traceback (most recent call last):
  File "d:\users\y7000\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\users\y7000\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\Users\y7000\anaconda3\Scripts\tidevice.exe\__main__.py", line 7, in <module>
  File "d:\users\y7000\anaconda3\lib\site-packages\tidevice\__main__.py", line 742, in main
    actions[args.subparser](args)
  File "d:\users\y7000\anaconda3\lib\site-packages\tidevice\__main__.py", line 237, in cmd_xctest
    d.xctest(args.bundle_id,
  File "d:\users\y7000\anaconda3\lib\site-packages\tidevice\_device.py", line 973, in xctest
    x1 = self._connect_testmanagerd_lockdown()
  File "d:\users\y7000\anaconda3\lib\site-packages\tidevice\_device.py", line 769, in _connect_testmanagerd_lockdown
    conn = self.start_service(LockdownService.TestmanagerdLockdown)
  File "d:\users\y7000\anaconda3\lib\site-packages\tidevice\_device.py", line 447, in start_service
    return self._unsafe_start_service(name)
  File "d:\users\y7000\anaconda3\lib\site-packages\tidevice\_device.py", line 476, in _unsafe_start_service
    conn = self.create_inner_connection(data['Port'], _ssl=_ssl)
  File "d:\users\y7000\anaconda3\lib\site-packages\tidevice\_device.py", line 287, in create_inner_connection
    self._usbmux._check(data)
  File "d:\users\y7000\anaconda3\lib\site-packages\tidevice\_usbmux.py", line 94, in _check
    raise MuxReplyError(data['Number'])
tidevice.exceptions.MuxReplyError: UsbmuxReplyCode.ConnectionRefused

**Comment by luxiaolan6373** [comment]
重启,重装,重写签名都试过了

**Comment by 13685512269** [comment]
有解决方案了吗？我也遇到这个问题

**Comment by luxiaolan6373** [comment]
解决了,,就是要越狱 然后要重新编译wda




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月5日(星期五) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/taobao-iphone-device] tidevice.exceptions.MuxReplyError: UsbmuxReplyCode.ConnectionRefused (#148)





 
有解决方案了吗？我也遇到这个问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by codeskyblue** [comment]
修复版本 0.6.11
主要问题原因，调用socket.dup() 复制socket之后，在使用完之后没有将其关闭。
跟我以前想象的不太一样，现在看来socket还是需要手动关闭才行。

![image](https://user-images.githubusercontent.com/3281689/159911589-45b59be9-32d9-4668-a21d-a145c749082d.png)

**Comment by luxiaolan6373** [comment]
因为不稳定很久都没用过了.谢谢回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月24日(星期四) 晚上7:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/taobao-iphone-device] tidevice.exceptions.MuxReplyError: UsbmuxReplyCode.ConnectionRefused (#148)





 
修复版本 0.6.11
 主要问题原因，调用socket.dup() 复制socket之后，在使用完之后没有将其关闭。
 跟我以前想象的不太一样，现在看来socket还是需要手动关闭才行。

**Comment by codeskyblue** [comment]
@luxiaolan6373 这个问题是好久了，现在可以用回来了哈。这个问题修好之后，我感觉用起来好很多了，不用每次重启手机了。

**Comment by luxiaolan6373** [comment]
哈哈

**Comment by anjingder** [comment]
大佬在吗

**Comment by vveimin** [comment]
大佬在嘛，我的版本已经升级到0.7.13了，但是还是会出现UsbmuxReplyCode.ConnectionRefused.这个报错，重启手机可以解决。这是为什么呀==

**Comment by haifengzuishuai** [comment]
新版本任然有这个问题C:\Windows\system32>tidevice -u 00008020-001A512226E9002E wdaproxy -B com.tospur.WebDriverAgentRunner.xctrunner --port 8100
[I 231209 20:36:04 _wdaproxy:128] [00008020-001A512226E9002E] WDA check every 30.0 seconds
[D 231209 20:36:04 _wdaproxy:134] [00008020-001A512226E9002E] launch WDA
[D 231209 20:36:04 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[I 231209 20:36:04 _device:996] BundleID: com.tospur.WebDriverAgentRunner.xctrunner
[I 231209 20:36:04 _device:1023] ProductVersion: 17.2
[I 231209 20:36:04 _device:1024] UDID: 00008020-001A512226E9002E
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 501, in start_service
    return self._unsafe_start_service(name)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 520, in _unsafe_start_service
    raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 1040, in <module>
    main()
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 1035, in main
    actions[args.subparser](args)
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 306, in cmd_xcuitest
    tests_to_run=tests_to_run)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 1002, in runwda
    tests_to_run=tests_to_run)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 1034, in xcuitest
    x1 = self._connect_testmanagerd_lockdown()
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 801, in _connect_testmanagerd_lockdown
    LockdownService.TestmanagerdLockdownSecure)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 503, in start_service
    self.mount_developer_image()
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 674, in mount_developer_image
    raise ServiceError("DeveloperImage not found")
tidevice.exceptions.ServiceError: DeveloperImage not found
[D 231209 20:36:05 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[E 231209 20:36:05 _wdaproxy:153] [00008020-001A512226E9002E] wda started failed
[D 231209 20:36:05 _wdaproxy:134] [00008020-001A512226E9002E] launch WDA
[D 231209 20:36:05 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[I 231209 20:36:05 _device:996] BundleID: com.tospur.WebDriverAgentRunner.xctrunner
[I 231209 20:36:05 _device:1023] ProductVersion: 17.2
[I 231209 20:36:05 _device:1024] UDID: 00008020-001A512226E9002E
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 501, in start_service
    return self._unsafe_start_service(name)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 520, in _unsafe_start_service
    raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 1040, in <module>
    main()
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 1035, in main
    actions[args.subparser](args)
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 306, in cmd_xcuitest
    tests_to_run=tests_to_run)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 1002, in runwda
    tests_to_run=tests_to_run)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 1034, in xcuitest
    x1 = self._connect_testmanagerd_lockdown()
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 801, in _connect_testmanagerd_lockdown
    LockdownService.TestmanagerdLockdownSecure)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 503, in start_service
    self.mount_developer_image()
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 674, in mount_developer_image
    raise ServiceError("DeveloperImage not found")
tidevice.exceptions.ServiceError: DeveloperImage not found
[D 231209 20:36:06 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[E 231209 20:36:06 _wdaproxy:153] [00008020-001A512226E9002E] wda started failed
[D 231209 20:36:06 _wdaproxy:134] [00008020-001A512226E9002E] launch WDA
[D 231209 20:36:06 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[I 231209 20:36:06 _device:996] BundleID: com.tospur.WebDriverAgentRunner.xctrunner
[I 231209 20:36:06 _device:1023] ProductVersion: 17.2
[I 231209 20:36:06 _device:1024] UDID: 00008020-001A512226E9002E
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 501, in start_service
    return self._unsafe_start_service(name)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 520, in _unsafe_start_service
    raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 1040, in <module>
    main()
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 1035, in main
    actions[args.subparser](args)
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 306, in cmd_xcuitest
    tests_to_run=tests_to_run)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 1002, in runwda
    tests_to_run=tests_to_run)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 1034, in xcuitest
    x1 = self._connect_testmanagerd_lockdown()
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 801, in _connect_testmanagerd_lockdown
    LockdownService.TestmanagerdLockdownSecure)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 503, in start_service
    self.mount_developer_image()
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 674, in mount_developer_image
    raise ServiceError("DeveloperImage not found")
tidevice.exceptions.ServiceError: DeveloperImage not found
[D 231209 20:36:07 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[E 231209 20:36:07 _wdaproxy:153] [00008020-001A512226E9002E] wda started failed
[D 231209 20:36:07 _wdaproxy:134] [00008020-001A512226E9002E] launch WDA
[D 231209 20:36:07 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[I 231209 20:36:07 _device:996] BundleID: com.tospur.WebDriverAgentRunner.xctrunner
[I 231209 20:36:07 _device:1023] ProductVersion: 17.2
[I 231209 20:36:07 _device:1024] UDID: 00008020-001A512226E9002E
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 501, in start_service
    return self._unsafe_start_service(name)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 520, in _unsafe_start_service
    raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 1040, in <module>
    main()
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 1035, in main
    actions[args.subparser](args)
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 306, in cmd_xcuitest
    tests_to_run=tests_to_run)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 1002, in runwda
    tests_to_run=tests_to_run)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 1034, in xcuitest
    x1 = self._connect_testmanagerd_lockdown()
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 801, in _connect_testmanagerd_lockdown
    LockdownService.TestmanagerdLockdownSecure)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 503, in start_service
    self.mount_developer_image()
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 674, in mount_developer_image
    raise ServiceError("DeveloperImage not found")
tidevice.exceptions.ServiceError: DeveloperImage not found
[D 231209 20:36:08 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[E 231209 20:36:08 _wdaproxy:153] [00008020-001A512226E9002E] wda started failed
[D 231209 20:36:08 _wdaproxy:134] [00008020-001A512226E9002E] launch WDA
[D 231209 20:36:08 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[I 231209 20:36:08 _device:996] BundleID: com.tospur.WebDriverAgentRunner.xctrunner
[I 231209 20:36:08 _device:1023] ProductVersion: 17.2
[I 231209 20:36:08 _device:1024] UDID: 00008020-001A512226E9002E
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 501, in start_service
    return self._unsafe_start_service(name)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 520, in _unsafe_start_service
    raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 1040, in <module>
    main()
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 1035, in main
    actions[args.subparser](args)
  File "c:\program files\python37\lib\site-packages\tidevice\__main__.py", line 306, in cmd_xcuitest
    tests_to_run=tests_to_run)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 1002, in runwda
    tests_to_run=tests_to_run)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 1034, in xcuitest
    x1 = self._connect_testmanagerd_lockdown()
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 801, in _connect_testmanagerd_lockdown
    LockdownService.TestmanagerdLockdownSecure)
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 503, in start_service
    self.mount_developer_image()
  File "c:\program files\python37\lib\site-packages\tidevice\_device.py", line 674, in mount_developer_image
    raise ServiceError("DeveloperImage not found")
tidevice.exceptions.ServiceError: DeveloperImage not found
[D 231209 20:36:09 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[E 231209 20:36:09 _wdaproxy:153] [00008020-001A512226E9002E] wda started failed

C:\Windows\system32>tidevice -u 00008020-001A512226E9002E wdaproxy -B com.tospur.WebDriverAgentRunner.xctrunner --port 8100 wda started failedtidevice
usage: tidevice [-h] [-v] [-u UDID] [--socket SOCKET] [--trace]
                {version,list,info,date,sysinfo,appinfo,applist,battery,screenshot,install,uninstall,reboot,shutdown,parse,watch,wait-for-device,launch,energy,kill,ps,relay,xcuitest,xctest,wdaproxy,syslog,fsync,crashreport,dumpfps,developer,pair,unpair,perf,set-assistive-touch,savesslfile,test}
                ...
tidevice: error: unrecognized arguments: wda started failedtidevice
^C
C:\Windows\system32>tidevice -u 00008020-001A512226E9002E wdaproxy -B com.tospur.WebDriverAgentRunner.xctrunner --port 8100 wda started failedtidevic
usage: tidevice [-h] [-v] [-u UDID] [--socket SOCKET] [--trace]
                {version,list,info,date,sysinfo,appinfo,applist,battery,screenshot,install,uninstall,reboot,shutdown,parse,watch,wait-for-device,launch,energy,kill,ps,relay,xcuitest,xctest,wdaproxy,syslog,fsync,crashreport,dumpfps,developer,pair,unpair,perf,set-assistive-touch,savesslfile,test}
                ...
tidevice: error: unrecognized arguments: wda started failedtidevic

C:\Windows\system32>tidevice version
tidevice version 0.12.5

**Comment by haifengzuishuai** [comment]
新版本任然有这个问题
C:\Windows\system32>tidevice -u 00008020-001A512226E9002E wdaproxy -B com.xxx.WebDriverAgentRunner.xctrunner --port 8100 wda started failedtidevic
usage: tidevice [-h] [-v] [-u UDID] [--socket SOCKET] [--trace]
                {version,list,info,date,sysinfo,appinfo,applist,battery,screenshot,install,uninstall,reboot,shutdown,parse,watch,wait-for-device,launch,energy,kill,ps,relay,xcuitest,xctest,wdaproxy,syslog,fsync,crashreport,dumpfps,developer,pair,unpair,perf,set-assistive-touch,savesslfile,test}
                ...
tidevice: error: unrecognized arguments: wda started failedtidevic

C:\Windows\system32>tidevice version
tidevice version 0.12.5

**Comment by haifengzuishuai** [comment]
C:\Windows\system32>tidevice version
tidevice version 0.12.5

C:\Windows\system32>tidevice -u 00008020-001A512226E9002E wdaproxy -B com.xxx.WebDriverAgentRunner.xctrunner --port 8100
[I 231209 20:42:43 _wdaproxy:128] [00008020-001A512226E9002E] WDA check every 30.0 seconds
[D 231209 20:42:43 _wdaproxy:134] [00008020-001A512226E9002E] launch WDA
[D 231209 20:42:43 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[I 231209 20:42:44 _device:996] BundleID: com.xxx.WebDriverAgentRunner.xctrunner
[I 231209 20:42:44 _device:1023] ProductVersion: 17.2
[I 231209 20:42:44 _device:1024] UDID: 00008020-001A512226E9002E
Traceback (most recent call last):
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 501, in start_service
return self._unsafe_start_service(name)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 520, in _unsafe_start_service
raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\program files\python37\lib\runpy.py", line 193, in run_module_as_main
"main", mod_spec)
File "c:\program files\python37\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "c:\program files\python37\lib\site-packages\tidevice_main.py", line 1040, in
main()
File "c:\program files\python37\lib\site-packages\tidevice_main.py", line 1035, in main
actions[args.subparser](https://github.com/alibaba/tidevice/issues/args)
File "c:\program files\python37\lib\site-packages\tidevice_main_.py", line 306, in cmd_xcuitest
tests_to_run=tests_to_run)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 1002, in runwda
tests_to_run=tests_to_run)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 1034, in xcuitest
x1 = self._connect_testmanagerd_lockdown()
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 801, in _connect_testmanagerd_lockdown
LockdownService.TestmanagerdLockdownSecure)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 503, in start_service
self.mount_developer_image()
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 674, in mount_developer_image
raise ServiceError("DeveloperImage not found")
tidevice.exceptions.ServiceError: DeveloperImage not found
[D 231209 20:42:44 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[E 231209 20:42:44 _wdaproxy:153] [00008020-001A512226E9002E] wda started failed
[D 231209 20:42:44 _wdaproxy:134] [00008020-001A512226E9002E] launch WDA
[D 231209 20:42:44 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[I 231209 20:42:45 _device:996] BundleID: com.xxx.WebDriverAgentRunner.xctrunner
[I 231209 20:42:45 _device:1023] ProductVersion: 17.2
[I 231209 20:42:45 _device:1024] UDID: 00008020-001A512226E9002E
Traceback (most recent call last):
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 501, in start_service
return self._unsafe_start_service(name)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 520, in _unsafe_start_service
raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\program files\python37\lib\runpy.py", line 193, in run_module_as_main
"main", mod_spec)
File "c:\program files\python37\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "c:\program files\python37\lib\site-packages\tidevice_main.py", line 1040, in
main()
File "c:\program files\python37\lib\site-packages\tidevice_main.py", line 1035, in main
actions[args.subparser](https://github.com/alibaba/tidevice/issues/args)
File "c:\program files\python37\lib\site-packages\tidevice_main_.py", line 306, in cmd_xcuitest
tests_to_run=tests_to_run)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 1002, in runwda
tests_to_run=tests_to_run)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 1034, in xcuitest
x1 = self._connect_testmanagerd_lockdown()
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 801, in _connect_testmanagerd_lockdown
LockdownService.TestmanagerdLockdownSecure)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 503, in start_service
self.mount_developer_image()
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 674, in mount_developer_image
raise ServiceError("DeveloperImage not found")
tidevice.exceptions.ServiceError: DeveloperImage not found
[D 231209 20:42:45 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[E 231209 20:42:45 _wdaproxy:153] [00008020-001A512226E9002E] wda started failed
[D 231209 20:42:45 _wdaproxy:134] [00008020-001A512226E9002E] launch WDA
[D 231209 20:42:45 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[I 231209 20:42:46 _device:996] BundleID: com.xxx.WebDriverAgentRunner.xctrunner
[I 231209 20:42:46 _device:1023] ProductVersion: 17.2
[I 231209 20:42:46 _device:1024] UDID: 00008020-001A512226E9002E
Traceback (most recent call last):
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 501, in start_service
return self._unsafe_start_service(name)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 520, in _unsafe_start_service
raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\program files\python37\lib\runpy.py", line 193, in run_module_as_main
"main", mod_spec)
File "c:\program files\python37\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "c:\program files\python37\lib\site-packages\tidevice_main.py", line 1040, in
main()
File "c:\program files\python37\lib\site-packages\tidevice_main.py", line 1035, in main
actions[args.subparser](https://github.com/alibaba/tidevice/issues/args)
File "c:\program files\python37\lib\site-packages\tidevice_main_.py", line 306, in cmd_xcuitest
tests_to_run=tests_to_run)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 1002, in runwda
tests_to_run=tests_to_run)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 1034, in xcuitest
x1 = self._connect_testmanagerd_lockdown()
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 801, in _connect_testmanagerd_lockdown
LockdownService.TestmanagerdLockdownSecure)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 503, in start_service
self.mount_developer_image()
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 674, in mount_developer_image
raise ServiceError("DeveloperImage not found")
tidevice.exceptions.ServiceError: DeveloperImage not found
[D 231209 20:42:46 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[E 231209 20:42:46 _wdaproxy:153] [00008020-001A512226E9002E] wda started failed
[D 231209 20:42:46 _wdaproxy:134] [00008020-001A512226E9002E] launch WDA
[D 231209 20:42:46 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[I 231209 20:42:47 _device:996] BundleID: com.xxx.WebDriverAgentRunner.xctrunner
[I 231209 20:42:47 _device:1023] ProductVersion: 17.2
[I 231209 20:42:47 _device:1024] UDID: 00008020-001A512226E9002E
Traceback (most recent call last):
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 501, in start_service
return self._unsafe_start_service(name)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 520, in _unsafe_start_service
raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\program files\python37\lib\runpy.py", line 193, in run_module_as_main
"main", mod_spec)
File "c:\program files\python37\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "c:\program files\python37\lib\site-packages\tidevice_main.py", line 1040, in
main()
File "c:\program files\python37\lib\site-packages\tidevice_main.py", line 1035, in main
actions[args.subparser](https://github.com/alibaba/tidevice/issues/args)
File "c:\program files\python37\lib\site-packages\tidevice_main_.py", line 306, in cmd_xcuitest
tests_to_run=tests_to_run)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 1002, in runwda
tests_to_run=tests_to_run)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 1034, in xcuitest
x1 = self._connect_testmanagerd_lockdown()
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 801, in _connect_testmanagerd_lockdown
LockdownService.TestmanagerdLockdownSecure)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 503, in start_service
self.mount_developer_image()
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 674, in mount_developer_image
raise ServiceError("DeveloperImage not found")
tidevice.exceptions.ServiceError: DeveloperImage not found
[D 231209 20:42:47 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[E 231209 20:42:47 _wdaproxy:153] [00008020-001A512226E9002E] wda started failed
[D 231209 20:42:47 _wdaproxy:134] [00008020-001A512226E9002E] launch WDA
[D 231209 20:42:47 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[I 231209 20:42:48 _device:996] BundleID: com.xxx.WebDriverAgentRunner.xctrunner
[I 231209 20:42:48 _device:1023] ProductVersion: 17.2
[I 231209 20:42:48 _device:1024] UDID: 00008020-001A512226E9002E
Traceback (most recent call last):
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 501, in start_service
return self._unsafe_start_service(name)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 520, in _unsafe_start_service
raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\program files\python37\lib\runpy.py", line 193, in run_module_as_main
"main", mod_spec)
File "c:\program files\python37\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "c:\program files\python37\lib\site-packages\tidevice_main.py", line 1040, in
main()
File "c:\program files\python37\lib\site-packages\tidevice_main.py", line 1035, in main
actions[args.subparser](https://github.com/alibaba/tidevice/issues/args)
File "c:\program files\python37\lib\site-packages\tidevice_main_.py", line 306, in cmd_xcuitest
tests_to_run=tests_to_run)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 1002, in runwda
tests_to_run=tests_to_run)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 1034, in xcuitest
x1 = self._connect_testmanagerd_lockdown()
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 801, in _connect_testmanagerd_lockdown
LockdownService.TestmanagerdLockdownSecure)
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 503, in start_service
self.mount_developer_image()
File "c:\program files\python37\lib\site-packages\tidevice_device.py", line 674, in mount_developer_image
raise ServiceError("DeveloperImage not found")
tidevice.exceptions.ServiceError: DeveloperImage not found
[D 231209 20:42:48 _wdaproxy:58] [00008020-001A512226E9002E] request error: ('Connection aborted.', MuxReplyError(<UsbmuxReplyCode.ConnectionRefused: 3>))
[E 231209 20:42:48 _wdaproxy:153] [00008020-001A512226E9002E] wda started failed
新版本任然有这个问题

**Comment by likaimin1985** [comment]
> 你用的有线还是无线，我用有线没问题，无线会有这个问题，通过另外一个框架，看是这个错误原因如下：
> 
> DTDKRemoteDeviceConnection: Failed to start remote service "com.apple.instruments.remoteserver.DVTSecureSocketProxy" on device. Error: Error Domain=com.apple.dtdevicekit Code=811 "Failed to start remote service "com.apple.instruments.remoteserver.DVTSecureSocketProxy" on device." UserInfo={NSUnderlyingError=0x7fdb4355c3b0 {Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402653150 "The service is invalid." UserInfo={MobileDeviceErrorCode=(0xE8000022), com.apple.dtdevicekit.stacktrace=
请问大佬这个问题怎么解决，困扰我好久了

**Comment by codeskyblue** [comment]
看起来这个问题还是没有完全消灭
https://github.com/doronz88/pymobiledevice3/issues/784
