### ISSUE TITLE
iOS15系统，启动wda时，报错

### ISSUE THREAD

**Issue by lycfr** [alibaba/taobao-iphone-device#156]
```
MacBook-Pro:~ $ tidevice xctest -B com.facebook.WebDriverAgentRunner.xctrunner
[I 211027 10:32:48 _device:996] BundleID: com.facebook.WebDriverAgentRunner.xctrunner
[I 211027 10:32:48 _device:998] DeviceIdentifier: 9941e2ce2018cd02c295b0108ee30b0c6e64b7f8
[I 211027 10:32:48 _device:572] ProductVersion: 15.0
[I 211027 10:32:48 _device:551] Download https://tool.appetizer.io/iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/15.0.zip -> /Users/hhh/.tidevice/device-support/15.0.zip
[I 211027 10:32:49 _device:551] Download https://github.com/iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/15.0.zip -> /Users/hhh/.tidevice/device-support/15.0.zip
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_device.py", line 454, in start_service
    return self._unsafe_start_service(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_device.py", line 471, in _unsafe_start_service
    "Remember that you have to mount the Developer disk image on your device"
tidevice.exceptions.MuxServiceError: Could not start service: com.apple.testmanagerd.lockdown.secure! Remember that you have to mount the Developer disk image on your device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_device.py", line 607, in _request_developer_image_dir
    self._urlretrieve(mirror_url, image_zip_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_device.py", line 556, in _urlretrieve
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://tool.appetizer.io/iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/15.0.zip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/tidevice", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/__main__.py", line 689, in main
    actions[args.subparser](args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/__main__.py", line 231, in cmd_xctest
    env=env)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_device.py", line 1008, in xctest
    x1 = self._connect_testmanagerd_lockdown()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_device.py", line 805, in _connect_testmanagerd_lockdown
    LockdownService.TestmanagerdLockdownSecure)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_device.py", line 456, in start_service
    self.mount_developer_image()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_device.py", line 648, in mount_developer_image
    with self._request_developer_image_dir() as _dir: #, signature_path:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_device.py", line 611, in _request_developer_image_dir
    self._urlretrieve(origin_url, image_zip_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_device.py", line 556, in _urlretrieve
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/15.0.zip
```
看提示好像是镜像链接的问题

**Comment by codeskyblue** [comment]
最新版应该已经换成了从这个项目下载image了
https://github.com/JinjunHan/iOSDeviceSupport/tree/master/DeviceSupport

你更新一下tidevice就可以了

**Comment by pkm1118** [comment]
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/14.6   tidevice wdaproxy
[I 220530 14:44:48 _wdaproxy:125] [d7d15615997597abff977fb66843ff1996c644b8] WDA check every 30.0 seconds
[D 220530 14:44:48 _wdaproxy:131] [d7d15615997597abff977fb66843ff1996c644b8] launch WDA
[I 220530 14:44:49 _device:969] BundleID: com.facebook.d7d15615997597abff977fb66843ff1996c644b8.WebDriverAgentRunner.xctrunner
[I 220530 14:44:49 _device:985] ProductVersion: 14.6
[I 220530 14:44:49 _device:986] DeviceIdentifier: d7d15615997597abff977fb66843ff1996c644b8
[I 220530 14:44:49 _device:607] ProductVersion: 14.6
[I 220530 14:44:49 _imagemounter:157] Pushing DeveloperDiskImage.dmg
[I 220530 14:44:50 _imagemounter:170] Push complete
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_device.py", line 492, in start_service
    return self._unsafe_start_service(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_device.py", line 508, in _unsafe_start_service
    raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/__main__.py", line 871, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/__main__.py", line 866, in main
    actions[args.subparser](args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/__main__.py", line 259, in cmd_xctest
    d.xctest(args.bundle_id,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_device.py", line 970, in xctest
    return self.xcuitest(bundle_id, target_bundle_id=target_bundle_id, logger=logger, env=env)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_device.py", line 996, in xcuitest
    x1 = self._connect_testmanagerd_lockdown()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_device.py", line 791, in _connect_testmanagerd_lockdown
    conn = self.start_service(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_device.py", line 494, in start_service
    self.mount_developer_image()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_device.py", line 668, in mount_developer_image
    self.imagemounter.mount(image_path, signature_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_imagemounter.py", line 139, in mount
    return self.mount_fileobj(image_reader, image_size, signature_content)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_imagemounter.py", line 182, in mount_fileobj
    self._check_error(ret)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_imagemounter.py", line 123, in _check_error
    raise MuxError(ret['Error'])
tidevice.exceptions.MuxError: ImageMountFailed`
这个一直挂在失败，知道是什么问题吗，已经将自动下载的14.6对应的DeveloperDiskImage.dmg放到/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/14.6 目录中，但还是失败

**Comment by codeskyblue** [comment]
@pkm1118 重启试试？

**Comment by pkm1118** [comment]
@[codeskyblue](https://github.com/codeskyblue)我电脑手机都重启过，还是不行

**Comment by oslo254804746** [comment]
+1, 13 pro max 挂不进去

**Comment by abeelan** [comment]
遇到了同样的问题。昨天还能正常使用，今天启动 wda 服务报错：`tidevice.exceptions.MuxError: ImageMountFailed`

### 问题
手动执行挂载命令，出现同样的错误。
```shell
$ tidevice developer
[I 220908 10:13:03 _device:602] ProductVersion: 15.4
[I 220908 10:13:03 _imagemounter:157] Pushing DeveloperDiskImage.dmg
[I 220908 10:13:03 _imagemounter:170] Push complete
Traceback (most recent call last):
  File "/usr/local/bin/tidevice", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tidevice/__main__.py", line 951, in main
    actions[args.subparser](args)
  File "/usr/local/lib/python3.7/site-packages/tidevice/__main__.py", line 448, in cmd_developer
    d.mount_developer_image()
  File "/usr/local/lib/python3.7/site-packages/tidevice/_device.py", line 663, in mount_developer_image
    self.imagemounter.mount(image_path, signature_path)
  File "/usr/local/lib/python3.7/site-packages/tidevice/_imagemounter.py", line 139, in mount
    return self.mount_fileobj(image_reader, image_size, signature_content)
  File "/usr/local/lib/python3.7/site-packages/tidevice/_imagemounter.py", line 182, in mount_fileobj
    self._check_error(ret)
  File "/usr/local/lib/python3.7/site-packages/tidevice/_imagemounter.py", line 123, in _check_error
    raise MuxError(ret['Error'])
tidevice.exceptions.MuxError: ImageMountFailed
```

### 尝试

`$ tidevice developer --download-all` 下载全部镜像是可以正常下载的，网络没问题。

> 最新版应该已经换成了从这个项目下载image了 https://github.com/JinjunHan/iOSDeviceSupport/tree/master/DeviceSupport
> 
> 你更新一下tidevice就可以了

1. 更新 tidevice，当前版本为 `tidevice version 0.9.11`，未解决；
2. 手动下载 15.4 的镜像并放到 `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/`目录下，未解决。
