### ISSUE TITLE
tidevice 安装成功了，但是tidevice applist  报错

### ISSUE THREAD

**Issue by Nnnnnnnnnical** [alibaba/taobao-iphone-device#182]
Traceback (most recent call last):
  File "/usr/local/bin/tidevice", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/tidevice/__main__.py", line 760, in main
    actions[args.subparser](args)
  File "/usr/local/lib/python3.9/site-packages/tidevice/__main__.py", line 266, in cmd_applist
    for info in d.installation.iter_installed():
  File "/usr/local/lib/python3.9/site-packages/tidevice/_installation.py", line 173, in iter_installed
    self.send_packet({
  File "/usr/local/lib/python3.9/site-packages/tidevice/_safe_socket.py", line 138, in send_packet
    logger.debug("SEND(%d): %s", self.id, payload)
  File "/usr/local/lib/python3.9/site-packages/tidevice/_safe_socket.py", line 62, in id
    return self._id
AttributeError: 'Installation' object has no attribute '_id'

**Comment by codeskyblue** [comment]
fixed in 0.6.1
