### ISSUE TITLE
ios 13.6.1 启动 WebDriverAgentRunner会包socket.timeout: timed out

### ISSUE THREAD

**Issue by 1x012** [alibaba/taobao-iphone-device#207]
ios 13.6.1 启动 WebDriverAgentRunner会包socket.timeout: timed out
，目前其他系统14.2的和12.4的是正常的

**Comment by 1x012** [comment]
有没有大佬帮忙看看呀E 220712 14:17:44 _instruments:574] drain error
    Traceback (most recent call last):
      File "e:\python37\lib\site-packages\tidevice\_instruments.py", line 564, in _drain
        self._drain_single_message()
      File "e:\python37\lib\site-packages\tidevice\_instruments.py", line 587, in _drain_single_message
        mheader, payload = self.recv_dtx_message()
      File "e:\python37\lib\site-packages\tidevice\_instruments.py", line 481, in recv_dtx_message
        data = self.psock.recvall(0x20)
      File "e:\python37\lib\site-packages\tidevice\_safe_socket.py", line 101, in recvall
        chunk = self._sock.recv(size - len(buf))
    OSError: [WinError 10038] 在一个非套接字上尝试了一个操作。
[E 220712 14:17:44 _instruments:574] drain error
    Traceback (most recent call last):
      File "e:\python37\lib\site-packages\tidevice\_instruments.py", line 564, in _drain
        self._drain_single_message()
      File "e:\python37\lib\site-packages\tidevice\_instruments.py", line 587, in _drain_single_message
        mheader, payload = self.recv_dtx_message()
      File "e:\python37\lib\site-packages\tidevice\_instruments.py", line 481, in recv_dtx_message
        data = self.psock.recvall(0x20)
      File "e:\python37\lib\site-packages\tidevice\_safe_socket.py", line 101, in recvall
        chunk = self._sock.recv(size - len(buf))
    OSError: [WinError 10038] 在一个非套接字上尝试了一个操作。

**Comment by 1x012** [comment]
不用了，tidevice升级一下解决了
