### ISSUE TITLE
手机重启后tidevice在win10无法正常启动WDA

### ISSUE THREAD

**Issue by HongFei1998** [alibaba/taobao-iphone-device#208]
发现手机重启一次后，在win10启动命令tidevice -u udid wdaproxy -B com.facebook.WebDriverAgentRunner.xxxx.xctrunner --port 8100就会出问题，但是在mac上执行同样的命令就会启动成功，之后再次拿到win10执行就又可以成功，下面是win10执行命令报错信息：

[D 220420 15:46:14 _wdaproxy:118] [00008101-001A24981E80001E] launch WDA
[I 220420 15:46:14 _device:554] ProductVersion: 15.4
Traceback (most recent call last):
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 453, in start_service
    return self._unsafe_start_service(name)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 468, in _unsafe_start_service
    raise MuxServiceError("Could not start service: {0}! {2}".format(
tidevice.exceptions.MuxServiceError: Could not start service: com.apple.mobile.installation_proxy! Remember that you have to mount the Developer disk image on your device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\anaconda\anaconda\envs\uitest\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\software\anaconda\anaconda\envs\uitest\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 717, in <module>
    main()
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 712, in main
    actions[args.subparser](args)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 229, in cmd_xctest
    d.xctest(args.bundle_id,
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 955, in xctest
    bundle_id = self._fnmatch_find_bundle_id(fuzzy_bundle_id)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 932, in _fnmatch_find_bundle_id
    for binfo in self.installation.iter_installed(
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 536, in installation
    conn = self.start_service(Installation.SERVICE_NAME)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 455, in start_service
    self.mount_developer_image()
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 608, in mount_developer_image
    with self._request_developer_image_dir() as _dir: #, signature_path:
  File "D:\software\anaconda\anaconda\envs\uitest\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 582, in _request_developer_image_dir
    raise RuntimeError("deviceSupport zip not detected DeveloperDiskImage")
RuntimeError: deviceSupport zip not detected DeveloperDiskImage
[E 220420 15:46:15 _wdaproxy:137] [00008101-001A24981E80001E] wda started failed
[D 220420 15:46:15 _wdaproxy:118] [00008101-001A24981E80001E] launch WDA
[I 220420 15:46:15 _device:554] ProductVersion: 15.4
Traceback (most recent call last):
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 453, in start_service
    return self._unsafe_start_service(name)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 468, in _unsafe_start_service
    raise MuxServiceError("Could not start service: {0}! {2}".format(
tidevice.exceptions.MuxServiceError: Could not start service: com.apple.mobile.installation_proxy! Remember that you have to mount the Developer disk image on your device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\anaconda\anaconda\envs\uitest\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\software\anaconda\anaconda\envs\uitest\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 717, in <module>
    main()
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 712, in main
    actions[args.subparser](args)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 229, in cmd_xctest
    d.xctest(args.bundle_id,
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 955, in xctest
    bundle_id = self._fnmatch_find_bundle_id(fuzzy_bundle_id)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 932, in _fnmatch_find_bundle_id
    for binfo in self.installation.iter_installed(
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 536, in installation
    conn = self.start_service(Installation.SERVICE_NAME)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 455, in start_service
    self.mount_developer_image()
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 608, in mount_developer_image
    with self._request_developer_image_dir() as _dir: #, signature_path:
  File "D:\software\anaconda\anaconda\envs\uitest\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 582, in _request_developer_image_dir
    raise RuntimeError("deviceSupport zip not detected DeveloperDiskImage")
RuntimeError: deviceSupport zip not detected DeveloperDiskImage
[E 220420 15:46:16 _wdaproxy:137] [00008101-001A24981E80001E] wda started failed
[D 220420 15:46:16 _wdaproxy:118] [00008101-001A24981E80001E] launch WDA
[I 220420 15:46:16 _device:554] ProductVersion: 15.4
Traceback (most recent call last):
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 453, in start_service
    return self._unsafe_start_service(name)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 468, in _unsafe_start_service
    raise MuxServiceError("Could not start service: {0}! {2}".format(
tidevice.exceptions.MuxServiceError: Could not start service: com.apple.mobile.installation_proxy! Remember that you have to mount the Developer disk image on your device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\anaconda\anaconda\envs\uitest\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\software\anaconda\anaconda\envs\uitest\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 717, in <module>
    main()
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 712, in main
    actions[args.subparser](args)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 229, in cmd_xctest
    d.xctest(args.bundle_id,
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 955, in xctest
    bundle_id = self._fnmatch_find_bundle_id(fuzzy_bundle_id)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 932, in _fnmatch_find_bundle_id
    for binfo in self.installation.iter_installed(
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 536, in installation
    conn = self.start_service(Installation.SERVICE_NAME)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 455, in start_service
    self.mount_developer_image()
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 608, in mount_developer_image
    with self._request_developer_image_dir() as _dir: #, signature_path:
  File "D:\software\anaconda\anaconda\envs\uitest\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 582, in _request_developer_image_dir
    raise RuntimeError("deviceSupport zip not detected DeveloperDiskImage")
RuntimeError: deviceSupport zip not detected DeveloperDiskImage
[E 220420 15:46:17 _wdaproxy:137] [00008101-001A24981E80001E] wda started failed
[D 220420 15:46:17 _wdaproxy:118] [00008101-001A24981E80001E] launch WDA
[I 220420 15:46:17 _device:554] ProductVersion: 15.4
Traceback (most recent call last):
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 453, in start_service
    return self._unsafe_start_service(name)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 468, in _unsafe_start_service
    raise MuxServiceError("Could not start service: {0}! {2}".format(
tidevice.exceptions.MuxServiceError: Could not start service: com.apple.mobile.installation_proxy! Remember that you have to mount the Developer disk image on your device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\anaconda\anaconda\envs\uitest\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\software\anaconda\anaconda\envs\uitest\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 717, in <module>
    main()
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 712, in main
    actions[args.subparser](args)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 229, in cmd_xctest
    d.xctest(args.bundle_id,
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 955, in xctest
    bundle_id = self._fnmatch_find_bundle_id(fuzzy_bundle_id)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 932, in _fnmatch_find_bundle_id
    for binfo in self.installation.iter_installed(
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 536, in installation
    conn = self.start_service(Installation.SERVICE_NAME)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 455, in start_service
    self.mount_developer_image()
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 608, in mount_developer_image
    with self._request_developer_image_dir() as _dir: #, signature_path:
  File "D:\software\anaconda\anaconda\envs\uitest\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 582, in _request_developer_image_dir
    raise RuntimeError("deviceSupport zip not detected DeveloperDiskImage")
RuntimeError: deviceSupport zip not detected DeveloperDiskImage
[E 220420 15:46:18 _wdaproxy:137] [00008101-001A24981E80001E] wda started failed
[D 220420 15:46:18 _wdaproxy:118] [00008101-001A24981E80001E] launch WDA
[I 220420 15:46:18 _device:554] ProductVersion: 15.4
Traceback (most recent call last):
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 453, in start_service
    return self._unsafe_start_service(name)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 468, in _unsafe_start_service
    raise MuxServiceError("Could not start service: {0}! {2}".format(
tidevice.exceptions.MuxServiceError: Could not start service: com.apple.mobile.installation_proxy! Remember that you have to mount the Developer disk image on your device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\anaconda\anaconda\envs\uitest\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\software\anaconda\anaconda\envs\uitest\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 717, in <module>
    main()
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 712, in main
    actions[args.subparser](args)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\__main__.py", line 229, in cmd_xctest
    d.xctest(args.bundle_id,
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 955, in xctest
    bundle_id = self._fnmatch_find_bundle_id(fuzzy_bundle_id)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 932, in _fnmatch_find_bundle_id
    for binfo in self.installation.iter_installed(
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 536, in installation
    conn = self.start_service(Installation.SERVICE_NAME)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 455, in start_service
    self.mount_developer_image()
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 608, in mount_developer_image
    with self._request_developer_image_dir() as _dir: #, signature_path:
  File "D:\software\anaconda\anaconda\envs\uitest\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\software\anaconda\anaconda\envs\uitest\lib\site-packages\tidevice\_device.py", line 582, in _request_developer_image_dir
    raise RuntimeError("deviceSupport zip not detected DeveloperDiskImage")
RuntimeError: deviceSupport zip not detected DeveloperDiskImage
[D 220420 15:46:18 _relay:36] handle stream from: ('127.0.0.1', 63923)
[E 220420 15:46:18 _relay:46] connect to device error: UsbmuxReplyCode.ConnectionRefused

**Comment by HongFei1998** [comment]
知道如何解决了，必须使用 pip3 install -U "tidevice[openssl]" 才可以正常使用
