### ISSUE TITLE
iphone6s plus 14.4.2采集性能数据直接报错了

### ISSUE THREAD

**Issue by lycfr** [alibaba/taobao-iphone-device#209]
```
cfr@MacBook-Pro-3 ~ % tidevice perf -B com.ly.tcent.tcentmobilemanager
[I 220421 10:46:50 _device:646] DeveloperImage already mounted
Stopped
Traceback (most recent call last):
  File "/Users/cfr/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tidevice/_device.py", line 491, in start_service
    return self._unsafe_start_service(name)
  File "/Users/cfr/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tidevice/_device.py", line 507, in _unsafe_start_service
    raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cfr/.pyenv/versions/3.6.5/bin/tidevice", line 8, in <module>
    sys.exit(main())
  File "/Users/cfr/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tidevice/__main__.py", line 866, in main
    actions[args.subparser](args)
  File "/Users/cfr/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tidevice/__main__.py", line 557, in cmd_perf
    perf.start(args.bundle_id, callback=_cb)
  File "/Users/cfr/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tidevice/_perf.py", line 298, in start
    self._rp = RunningProcess(self._d, bundle_id)
  File "/Users/cfr/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tidevice/_perf.py", line 36, in __init__
    self._ins = d.instruments
  File "/Users/cfr/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tidevice/_device.py", line 803, in instruments
    return self.connect_instruments()
  File "/Users/cfr/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tidevice/_device.py", line 793, in connect_instruments
    LockdownService.InstrumentsRemoteServerSecure)
  File "/Users/cfr/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tidevice/_device.py", line 496, in start_service
    return self._unsafe_start_service(name)
  File "/Users/cfr/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tidevice/_device.py", line 507, in _unsafe_start_service
    raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService
```
报错内容如上

**Comment by codeskyblue** [comment]
这个我不太懂确定原因，你先升级到最新版，然后重启一下手机试试
