### ISSUE TITLE
调用applist API报错

### ISSUE THREAD

**Issue by tinysheepyang** [alibaba/taobao-iphone-device#214]
[ E 220509 23:41:23 _instruments:573 ] drain error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_instruments.py", line 563, in _drain
    self._drain_single_message()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_instruments.py", line 586, in _drain_single_message
    mheader, payload = self.recv_dtx_message()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_instruments.py", line 480, in recv_dtx_message
    data = self.psock.recvall(0x20)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_safe_socket.py", line 88, in recvall
    chunk = self._sock.recv(size - len(buf))
socket.timeout: timed out
[ D 220509 23:41:23 _instruments:575 ] dtxm socket closed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/xxxx/Documents/code/xxxxxx/dist_electron/pyflask/api.py", line 343, in ios_app_list
    applist = instruments.app_list()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_instruments.py", line 740, in app_list
    "com.apple.instruments.server.services.device.applictionListing")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_instruments.py", line 316, in make_channel
    result = self.call_message(0, '_requestChannelWithCode:identifier:', aux)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_instruments.py", line 361, in call_message
    return self.wait_reply(_id).result
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tidevice/_instruments.py", line 551, in wait_reply
    ret = self._reply_queues[message_id].get(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/queue.py", line 178, in get
    raise Empty
_queue.Empty

**Comment by codeskyblue** [comment]
版本号多少呀
