### ISSUE TITLE
启动wda报错

### ISSUE THREAD

**Issue by jiangqifan** [alibaba/taobao-iphone-device#219]
tidevice version: 0.7.13
iOS: 14.7

```
15:27:17 Traceback (most recent call last):
15:27:17   File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
15:27:17     return _run_code(code, main_globals, None,
15:27:17   File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
15:27:17     exec(code, run_globals)
15:27:17   File "/usr/local/lib/python3.9/site-packages/tidevice/__main__.py", line 871, in <module>
15:27:17     main()
15:27:17   File "/usr/local/lib/python3.9/site-packages/tidevice/__main__.py", line 866, in main
15:27:17     actions[args.subparser](args)
15:27:17   File "/usr/local/lib/python3.9/site-packages/tidevice/__main__.py", line 259, in cmd_xctest
15:27:17     d.xctest(args.bundle_id,
15:27:17   File "/usr/local/lib/python3.9/site-packages/tidevice/_device.py", line 970, in xctest
15:27:17     return self.xcuitest(bundle_id, target_bundle_id=target_bundle_id, logger=logger, env=env)
15:27:17   File "/usr/local/lib/python3.9/site-packages/tidevice/_device.py", line 1057, in xcuitest
15:27:17     _, pid = self._launch_app_runner(bundle_id, session_identifier,
15:27:17   File "/usr/local/lib/python3.9/site-packages/tidevice/_device.py", line 847, in _launch_app_runner
15:27:17     conn = self.connect_instruments()
15:27:17   File "/usr/local/lib/python3.9/site-packages/tidevice/_device.py", line 800, in connect_instruments
15:27:17     conn = self.start_service(
15:27:17   File "/usr/local/lib/python3.9/site-packages/tidevice/_device.py", line 492, in start_service
15:27:17     return self._unsafe_start_service(name)
15:27:17   File "/usr/local/lib/python3.9/site-packages/tidevice/_device.py", line 528, in _unsafe_start_service
15:27:17     conn = self.create_inner_connection(data['Port'], _ssl=_ssl, ssl_dial_only=ssl_dial_only)
15:27:17   File "/usr/local/lib/python3.9/site-packages/tidevice/_device.py", line 306, in create_inner_connection
15:27:17     conn.switch_to_ssl(self.ssl_pemfile_path)
15:27:17   File "/usr/local/lib/python3.9/site-packages/tidevice/_safe_socket.py", line 132, in switch_to_ssl
15:27:17     ssock = context.wrap_socket(self._sock, server_hostname="iphone.localhost")
15:27:17   File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
15:27:17     return self.sslsocket_class._create(
15:27:17   File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
15:27:17     self.do_handshake()
15:27:17   File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
15:27:17     self._sslobj.do_handshake()
15:27:17 socket.timeout: _ssl.c:1112: The handshake operation timed out
```

**Comment by codeskyblue** [comment]
我也不知道咋回事，以前查了好久，查出来一个socket连接没释放的问题，使用weakref修复好了之后。出现的概率低了。不过还是会出来。我也就只能重启手机了
