### ISSUE TITLE
无法启动xctest

### ISSUE THREAD

**Issue by jongyu** [alibaba/taobao-iphone-device#224]
- 执行命令
```
tidevice -u 00008101-001238483400801E xctest -B com.facebook.WebDriverAgentRunner.xctrunner
```

- 环境
```
Python 3.9.13
macOS 12.4 (M1芯片)
```

- 报错
```
[I 220531 20:59:36 _device:969] BundleID: com.facebook.WebDriverAgentRunner.xctrunner
[I 220531 20:59:36 _device:985] ProductVersion: 14.7.1
[I 220531 20:59:36 _device:986] DeviceIdentifier: 00008101-001238483400801E
Traceback (most recent call last):
  File "/opt/homebrew/bin/tidevice", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/tidevice/__main__.py", line 866, in main
    actions[args.subparser](args)
  File "/opt/homebrew/lib/python3.9/site-packages/tidevice/__main__.py", line 259, in cmd_xctest
    d.xctest(args.bundle_id,
  File "/opt/homebrew/lib/python3.9/site-packages/tidevice/_device.py", line 970, in xctest
    return self.xcuitest(bundle_id, target_bundle_id=target_bundle_id, logger=logger, env=env)
  File "/opt/homebrew/lib/python3.9/site-packages/tidevice/_device.py", line 996, in xcuitest
    x1 = self._connect_testmanagerd_lockdown()
  File "/opt/homebrew/lib/python3.9/site-packages/tidevice/_device.py", line 791, in _connect_testmanagerd_lockdown
    conn = self.start_service(
  File "/opt/homebrew/lib/python3.9/site-packages/tidevice/_device.py", line 492, in start_service
    return self._unsafe_start_service(name)
  File "/opt/homebrew/lib/python3.9/site-packages/tidevice/_device.py", line 528, in _unsafe_start_service
    conn = self.create_inner_connection(data['Port'], _ssl=_ssl, ssl_dial_only=ssl_dial_only)
  File "/opt/homebrew/lib/python3.9/site-packages/tidevice/_device.py", line 306, in create_inner_connection
    conn.switch_to_ssl(self.ssl_pemfile_path)
  File "/opt/homebrew/lib/python3.9/site-packages/tidevice/_safe_socket.py", line 132, in switch_to_ssl
    ssock = context.wrap_socket(self._sock, server_hostname="iphone.localhost")
  File "/opt/homebrew/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out
```

**Comment by wangchy0927** [comment]
@codeskyblue 兄弟这个有解吗？也经常遇到这个问题
