### ISSUE TITLE
【BUG】tidevice ps 报错

### ISSUE THREAD

**Issue by rafa0128** [alibaba/taobao-iphone-device#255]
[I 220905 17:40:27 _device:602] ProductVersion: 15.5
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tidevice/_device.py", line 484, in start_service
    return self._unsafe_start_service(name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tidevice/_device.py", line 503, in _unsafe_start_service
    raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/tidevice", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tidevice/__main__.py", line 951, in main
    actions[args.subparser](args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tidevice/__main__.py", line 582, in cmd_ps
    with d.connect_instruments() as ts:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tidevice/_device.py", line 796, in connect_instruments
    conn = self.start_service(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tidevice/_device.py", line 486, in start_service
    self.mount_developer_image()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tidevice/_device.py", line 663, in mount_developer_image
    self.imagemounter.mount(image_path, signature_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tidevice/_imagemounter.py", line 139, in mount
    return self.mount_fileobj(image_reader, image_size, signature_content)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tidevice/_imagemounter.py", line 153, in mount_fileobj
    self._check_error(ret)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tidevice/_imagemounter.py", line 123, in _check_error
    raise MuxError(ret['Error'])
tidevice.exceptions.MuxError: DeviceLocked

**Comment by codeskyblue** [comment]
这不是锁屏了吗？
