### ISSUE TITLE
重签名的wda启动报错，在mac上用xcode可以正常进行自动化

### ISSUE THREAD

**Issue by maomaokeen** [alibaba/taobao-iphone-device#26]
手机上的wda是重签名，目前在mac上可以正常运行自动化，win10上启动就报错，
启动命令：

```
tidevice wdaproxy -B com.qdm.WebDriverAgentRunner.xctrunner --port 8200
```

报错信息如下：

```
[D 210218 09:22:43 _wdaproxy:116] [2bdd9c5129393d4f0a3e209af99a212732e659a6] launch WDA
[I 210218 09:22:45 _device:917] BundleID: com.qdm.WebDriverAgentRunner.xctrunner
[I 210218 09:22:45 _device:919] DeviceIdentifier: 2bdd9c5129393d4f0a3e209af99a212732e659a6
[I 210218 09:22:45 _device:517] ProductVersion: 14.4
[I 210218 09:22:45 _device:496] Download https://tool.appetizer.io/iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/14.4(FromXcode_12.4(12D4e)).zip -> C:\Users\linkage\.tidevice\device-support\14.4.zip
Traceback (most recent call last):
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 399, in start_service
    return self._unsafe_start_service(name)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 414, in _unsafe_start_service
    raise MuxServiceError("Could not start service: {0}! {2}".format(
tidevice.exceptions.MuxServiceError: Could not start service: com.apple.testmanagerd.lockdown.secure! Remember that you have to mount the Developer disk image on your device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 496, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tool.appetizer.io', port=443): Max retries exceeded with url: /iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/14.4(FromXcode_12.4(12D4e)).zip (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\__main__.py", line 488, in <module>
    main()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\__main__.py", line 483, in main
    actions[args.subparser](args)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\__main__.py", line 210, in cmd_xctest
    d.xctest(args.bundle_id, logger=setup_logger(level=logging.INFO), env=env)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 929, in xctest
    x1 = self._connect_testmanagerd_lockdown()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 741, in _connect_testmanagerd_lockdown
    conn = self.start_service(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 401, in start_service
    self.mount_developer_image()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 585, in mount_developer_image
    with self._request_developer_image_dir() as _dir: #, signature_path:
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 550, in _request_developer_image_dir
    self._urlretrieve(mirror_url, image_zip_path)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 500, in _urlretrieve
    with requests.get(url, stream=True) as r:
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='tool.appetizer.io', port=443): Max retries exceeded with url: /iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/14.4(FromXcode_12.4(12D4e)).zip (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))
[E 210218 09:22:46 _wdaproxy:124] [2bdd9c5129393d4f0a3e209af99a212732e659a6] wda started failed
[D 210218 09:22:46 _wdaproxy:116] [2bdd9c5129393d4f0a3e209af99a212732e659a6] launch WDA
[I 210218 09:22:48 _device:917] BundleID: com.qdm.WebDriverAgentRunner.xctrunner
[I 210218 09:22:48 _device:919] DeviceIdentifier: 2bdd9c5129393d4f0a3e209af99a212732e659a6
[I 210218 09:22:49 _device:517] ProductVersion: 14.4
[I 210218 09:22:49 _device:496] Download https://tool.appetizer.io/iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/14.4(FromXcode_12.4(12D4e)).zip -> C:\Users\linkage\.tidevice\device-support\14.4.zip
Traceback (most recent call last):
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 399, in start_service
    return self._unsafe_start_service(name)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 414, in _unsafe_start_service
    raise MuxServiceError("Could not start service: {0}! {2}".format(
tidevice.exceptions.MuxServiceError: Could not start service: com.apple.testmanagerd.lockdown.secure! Remember that you have to mount the Developer disk image on your device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 496, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tool.appetizer.io', port=443): Max retries exceeded with url: /iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/14.4(FromXcode_12.4(12D4e)).zip (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\__main__.py", line 488, in <module>
    main()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\__main__.py", line 483, in main
    actions[args.subparser](args)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\__main__.py", line 210, in cmd_xctest
    d.xctest(args.bundle_id, logger=setup_logger(level=logging.INFO), env=env)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 929, in xctest
    x1 = self._connect_testmanagerd_lockdown()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 741, in _connect_testmanagerd_lockdown
    conn = self.start_service(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 401, in start_service
    self.mount_developer_image()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 585, in mount_developer_image
    with self._request_developer_image_dir() as _dir: #, signature_path:
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 550, in _request_developer_image_dir
    self._urlretrieve(mirror_url, image_zip_path)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 500, in _urlretrieve
    with requests.get(url, stream=True) as r:
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='tool.appetizer.io', port=443): Max retries exceeded with url: /iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/14.4(FromXcode_12.4(12D4e)).zip (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))
[E 210218 09:22:53 _wdaproxy:124] [2bdd9c5129393d4f0a3e209af99a212732e659a6] wda started failed
[D 210218 09:22:53 _wdaproxy:116] [2bdd9c5129393d4f0a3e209af99a212732e659a6] launch WDA
[I 210218 09:22:56 _device:917] BundleID: com.qdm.WebDriverAgentRunner.xctrunner
[I 210218 09:22:56 _device:919] DeviceIdentifier: 2bdd9c5129393d4f0a3e209af99a212732e659a6
[I 210218 09:22:56 _device:517] ProductVersion: 14.4
[I 210218 09:22:56 _device:496] Download https://tool.appetizer.io/iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/14.4(FromXcode_12.4(12D4e)).zip -> C:\Users\linkage\.tidevice\device-support\14.4.zip
Traceback (most recent call last):
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 399, in start_service
    return self._unsafe_start_service(name)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 414, in _unsafe_start_service
    raise MuxServiceError("Could not start service: {0}! {2}".format(
tidevice.exceptions.MuxServiceError: Could not start service: com.apple.testmanagerd.lockdown.secure! Remember that you have to mount the Developer disk image on your device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 496, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tool.appetizer.io', port=443): Max retries exceeded with url: /iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/14.4(FromXcode_12.4(12D4e)).zip (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\__main__.py", line 488, in <module>
    main()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\__main__.py", line 483, in main
    actions[args.subparser](args)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\__main__.py", line 210, in cmd_xctest
    d.xctest(args.bundle_id, logger=setup_logger(level=logging.INFO), env=env)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 929, in xctest
    x1 = self._connect_testmanagerd_lockdown()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 741, in _connect_testmanagerd_lockdown
    conn = self.start_service(
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 401, in start_service
    self.mount_developer_image()
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 585, in mount_developer_image
    with self._request_developer_image_dir() as _dir: #, signature_path:
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 550, in _request_developer_image_dir
    self._urlretrieve(mirror_url, image_zip_path)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\tidevice\_device.py", line 500, in _urlretrieve
    with requests.get(url, stream=True) as r:
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\linkage\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='tool.appetizer.io', port=443): Max retries exceeded with url: /iGhibli/iOS-DeviceSupport/raw/master/DeviceSupport/14.4(FromXcode_12.4(12D4e)).zip (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))
[E 210218 09:22:57 _wdaproxy:124] [2bdd9c5129393d4f0a3e209af99a212732e659a6] wda started failed

**Comment by maomaokeen** [comment]
公司网络需要代理的问题，用自己的热点就行了
