### ISSUE TITLE
iOS 15.7 tidevice截图和结束应用都报错“tidevice.exceptions.MuxError: ImageMountFailed”

### ISSUE THREAD

**Issue by Silence0789** [alibaba/taobao-iphone-device#264]
(base) PS C:\Users\renyi0301\Desktop> $picpath="ios_"+(Get-Date).ToString('yyyy-MM-dd-HH-mm-ss_fff')+".png";tidevice screenshot ${picpath}
Screenshot saved to ios_2022-10-12-16-29-42_020.png
[I 221012 16:29:44 _device:602] ProductVersion: 15.7
[I 221012 16:29:44 _imagemounter:157] Pushing DeveloperDiskImage.dmg
[I 221012 16:29:44 _imagemounter:170] Push complete
Traceback (most recent call last):
  File "D:\CodeIDE\Anaconda3\lib\site-packages\tidevice\_device.py", line 484, in start_service
    return self._unsafe_start_service(name)
  File "D:\CodeIDE\Anaconda3\lib\site-packages\tidevice\_device.py", line 503, in _unsafe_start_service
    raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CodeIDE\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\CodeIDE\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\CodeIDE\Anaconda3\Scripts\tidevice.exe\__main__.py", line 7, in <module>
  File "D:\CodeIDE\Anaconda3\lib\site-packages\tidevice\__main__.py", line 951, in main
    actions[args.subparser](args)
  File "D:\CodeIDE\Anaconda3\lib\site-packages\tidevice\__main__.py", line 278, in cmd_screenshot
    d.screenshot().convert("RGB").save(filename)
  File "D:\CodeIDE\Anaconda3\lib\site-packages\tidevice\_device.py", line 528, in screenshot
    return next(self.iter_screenshot())
  File "D:\CodeIDE\Anaconda3\lib\site-packages\tidevice\_device.py", line 533, in iter_screenshot
    conn = self.start_service(LockdownService.MobileScreenshotr)
  File "D:\CodeIDE\Anaconda3\lib\site-packages\tidevice\_device.py", line 486, in start_service
    self.mount_developer_image()
  File "D:\CodeIDE\Anaconda3\lib\site-packages\tidevice\_device.py", line 663, in mount_developer_image
    self.imagemounter.mount(image_path, signature_path)
  File "D:\CodeIDE\Anaconda3\lib\site-packages\tidevice\_imagemounter.py", line 139, in mount
    return self.mount_fileobj(image_reader, image_size, signature_content)
  File "D:\CodeIDE\Anaconda3\lib\site-packages\tidevice\_imagemounter.py", line 182, in mount_fileobj
    self._check_error(ret)
  File "D:\CodeIDE\Anaconda3\lib\site-packages\tidevice\_imagemounter.py", line 123, in _check_error
    raise MuxError(ret['Error'])
tidevice.exceptions.MuxError: ImageMountFailed

**Comment by codeskyblue** [comment]
15.7应该是增加了苹果的开发者模式导致的。
 tidevice 0.10.0 增加了对iOS16自动开启开发者模式的支持，15.7还没做兼容
