### ISSUE TITLE
【0.9.12】 执行 tidevice ps 指令报错

### ISSUE THREAD

**Issue by wwwwsy** [alibaba/taobao-iphone-device#274]
我们希望App一直处于启动状态，所以定时在检查App的运行状态tidevice ps。
每天都会出现批量报错。报错信息统计看基本每个设备每天都会出现2次报错。
怀疑过是设备连接过多造成的，之前链接18台设备，后来改到7台设备。但是还是会出现。

> 报错信息1
运行中app，指令执行出现异常内容：Traceback (most recent call last):  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/tidevice", line 8, in <module>    sys.exit(main())  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/__main__.py", line 742, in main    actions[args.subparser](args)  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/__main__.py", line 452, in cmd_ps    ps = list(d.instruments.app_process_list(app_infos))  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 708, in app_process_list    processes = self.app_running_processes()  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 681, in app_running_processes    retobj = self.call_message(identifier, "runningProcesses")  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 354, in call_message    channel = self.make_channel(channel)  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 315, in make_channel    result = self.call_message(0, '_requestChannelWithCode:identifier:', aux)  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 356, in call_message    _id = self.send_dtx_message(channel,  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 392, in send_dtx_message    self.sendall(data)  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_safe_socket.py", line 66, in sendall    return self._sock.sendall(data)  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1204, in sendall    v = self.send(byte_view[count:])  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1173, in send    return self._sslobj.write(data)ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:2485)

> 报错信息2
运行中app，指令执行出现异常内容：[E 221206 14:44:41 _instruments:594] drain error    Traceback (most recent call last):      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 580, in _drain        self._drain_single_message()      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 607, in _drain_single_message        mheader, payload = self.recv_dtx_message()      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 513, in recv_dtx_message        message_id = self.recv_part_dtx_message()      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 409, in recv_part_dtx_message        data = self.psock.recvall(0x20)      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_safe_socket.py", line 115, in recvall        raise ConnectionError("socket connection broken")    ConnectionError: socket connection brokenTraceback (most recent call last):  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/tidevice", line 8, in <module>    sys.exit(main())  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/__main__.py", line 965, in main    actions[args.subparser](args)  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/__main__.py", line 582, in cmd_ps    ps = list(ts.app_process_list(app_infos))  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 737, in app_process_list    processes = self.app_running_processes()  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 708, in app_running_processes    retobj = self.call_message(identifier, "runningProcesses")  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 357, in call_message    channel = self.make_channel(channel)  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 318, in make_channel    result = self.call_message(0, '_requestChannelWithCode:identifier:', aux)  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 363, in call_message    return self.wait_reply(_id).result  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice/_instruments.py", line 568, in wait_reply    raise ConnectionError("connection closed")ConnectionError: connection closed

**Comment by codeskyblue** [comment]
我也不知道怎么整？有时候只能重启手机
