### ISSUE TITLE
Drain error while launching your WebDriverAgent.ipa

### ISSUE THREAD

**Issue by EmpireST1** [alibaba/taobao-iphone-device#299]
Hello. I trying to run Appium IOS + Windows debugging.

But now i feel issue when i trying to run com.facebook.WebDriverAgentRunner

[https://downloader.disk.yandex.ru/preview/2741f4527d1982e6efcd1240fabbe4785e081e4e1d6cb000d915ac1d0331c853/6414e7fd/MzOTkVXXfZL-UxI-piDe9SeHC-Jem7uhkNjavZ4Lh7uvtKknbLp_XSprLI9EPVeH7WcCqMf466rkUVQM9rdJHQ%3D%3D?uid=0&filename=2023-03-17_21-17-53.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&owner_uid=0&tknv=v2&size=2048x2048](url)

`[E 230317 20:55:55 _instruments:621] drain error
    Traceback (most recent call last):
      File "c:\users\empire\appdata\local\programs\python\python38-32\lib\site-packages\tidevice\_instruments.py", line 607, in _drain
        self._drain_single_message()
      File "c:\users\empire\appdata\local\programs\python\python38-32\lib\site-packages\tidevice\_instruments.py", line 634, in _drain_single_message
        mheader, payload = self.recv_dtx_message()
      File "c:\users\empire\appdata\local\programs\python\python38-32\lib\site-packages\tidevice\_instruments.py", line 540, in recv_dtx_message
        message_id = self.recv_part_dtx_message()
      File "c:\users\empire\appdata\local\programs\python\python38-32\lib\site-packages\tidevice\_instruments.py", line 436, in recv_part_dtx_message
        data = self.psock.recvall(0x20)
      File "c:\users\empire\appdata\local\programs\python\python38-32\lib\site-packages\tidevice\_safe_socket.py", line 115, in recvall
        raise ConnectionError("socket connection broken")
    ConnectionError: socket connection broken`

Can u share me new WebDriverAgent.ipa?

**Comment by AliceHome** [comment]
这个问题是解决了吗？我今天也遇到了

**Comment by EmpireST1** [comment]
> 到

Partially, issue on webdriveragent.ipa
You should to try different webdrivers. On Mac OS same issue with this webdriveragent.ipa

**Comment by jeniva** [comment]
请问解决了吗，我也遇到这个错误了

**Comment by jeniva** [comment]
![image](https://github.com/alibaba/taobao-iphone-device/assets/8514029/13552f59-d511-47ce-9c56-036bc0e8356b)
