### ISSUE TITLE
_perf.py screenshot error

### ISSUE THREAD

**Issue by myungkyojung** [alibaba/taobao-iphone-device#325]
$ tidevice perf -B com.xxx.yyy

Exception in thread perf:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/tidevice/_perf.py", line 271, in append_data
    for _type, data in idata:
  File "/usr/local/lib/python3.11/site-packages/tidevice/_perf.py", line 247, in set_interval
    data = next(it)
           ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tidevice/_perf.py", line 127, in iter_screenshot
    buffered = BytesIO()
               ^^^^^^^
NameError: name 'BytesIO' is not defined. Did you mean: 'bytes'?

**Comment by Jaskyer** [comment]
_perf.py文件
127行，BytesIO()应该是io.BytesIO()
并且开头少导入了base64库
