### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by myungkyojung** [alibaba/taobao-iphone-device#338]
After executing the tidevice relay command, the following error occurs when receive a response message after requesting to the WDA.
=> OSError: [Errno 9] Bad file descriptor

Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10bcc90d0>>, <Task finished name='Task-6' coro=<RelayTCPServer._pipe_stream() done, defined at /usr/local/lib/python3.11/site-packages/tidevice/_relay.py:63> exception=OSError(9, 'Bad file descriptor')>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tornado/ioloop.py", line 738, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tornado/ioloop.py", line 762, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.11/site-packages/tidevice/_relay.py", line 83, in _pipe_stream
    plconn.close()
  File "/usr/local/lib/python3.11/site-packages/tidevice/_safe_socket.py", line 280, in close
    self._finalizer()
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tidevice/_safe_socket.py", line 89, in close
    self._finalizer()
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tidevice/_safe_socket.py", line 85, in _cleanup
    self._sock.shutdown(socket.SHUT_RDWR)
OSError: [Errno 9] Bad file descriptor

**Comment by QuXing9** [comment]
同样遇到这个问题，复现步骤：
1. 映射手机端口到主机
```
tidevice relay 9001 59000
```
2. 终端访问
```
curl "http://localhost:9001/xx"
```
3. 程序报错
```
OSError: [Errno 9] Bad file descriptor
```
好像是在下面这个commit引入的问题，望修复问题。
https://github.com/alibaba/taobao-iphone-device/commit/4518f165b9515c57e66aeee070e2b6b8e9cab796
