### ISSUE TITLE
tidevice install 出现 ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by jongyu** [alibaba/taobao-iphone-device#91]
```bash
[I 210511 09:48:57 _device:721] Download to tmp path: C:\Users\xxx\AppData\Local\Temp\tmpwcfshdrr\_tmp.ipa
[22.6 MB/s 4s] Copying 'C:\\Users\\xxx\\AppData\\Local\\Temp\\tmpwcfshdrr\\_tmp.ipa' to device... Traceback (most recent call last):
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\Scripts\tidevice.exe\__main__.py", line 7, in <module>
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\tidevice\__main__.py", line 669, in main
    actions[args.subparser](args)
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\tidevice\__main__.py", line 130, in cmd_install
    bundle_id = d.app_install(args.filepath_or_url)
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\tidevice\_device.py", line 751, in app_install
    afc.push_content(target_path, preader)
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\tidevice\_sync.py", line 328, in push_content
    chunk = buf.read(chunk_size)
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\tidevice\_utils.py", line 83, in read
    self._update(len(chunk))
  File "c:\users\xxx\appdata\local\programs\python\python39\lib\site-packages\tidevice\_utils.py", line 102, in _update
    bytes_per_second = self._copied / (time.time() - self._begin)
ZeroDivisionError: float division by zero
```
![image](https://user-images.githubusercontent.com/26176468/117747217-504ff300-b240-11eb-8f65-8260748562a1.png)

**Comment by jongyu** [comment]
tidevice版本：0.4.3
python版本：3.9.4
系统：Windows 10

**Comment by codeskyblue** [comment]
fixed in 0.4.4
